mode: "debug"
port: 8080
name: "MyApp"
version: "1.0.0"
start_time: "2024-10-09T10:00:00Z"
machine_id: 1
smms_token: "Your SMMS Token"

log:
  level: "info"
  filename: "app.log"
  max_size: 100
  max_age: 30
  max_backups: 10

mysql:
  host: "127.0.0.1"
  user: "root"
  password: "123456"
  dbname: "bluebell"
  port: 3306
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  password: ""
  port: 6379
  db: 0
  pool_size: 10
  min_idle_conns: 5
